[build]
  command = "yarn generate"
  functions = "/functions"

[dev]
  command='yarn dev'
  port=3000

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
